### ISSUE TITLE
latest tag not updated in quay.io

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-plugin-image-builder#27]
## Describe the bug

After updating the [kubeconfig plugin](https://github.com/arcalot/arcaflow-plugin-kubeconfig) main branch with a PR, the new build automation successfully pushed a new container image with a commit tag, but the `latest` tag has not updated to point to a new build from the latest main code.

https://quay.io/repository/arcalot/arcaflow-plugin-kubeconfig?tab=tags

**Comment by jdowni000** [comment]
https://github.com/arcalot/arcaflow-plugin-kubeconfig/pull/7
